version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - redis
    networks:
      - app_network
  redis:
    image: redis:alpine
    networks:
      - app_network
networks:
  app_network:
